---
- name: test
  hosts: all
  remote_user: root
  tasks:
   - name: check the date on server
     command: date
     tags: date
     when: date is defined and date == 'yes'
   - name: check the ip addr
     command: ip addr
     tags: ip
